language: node_js
node_js:
  - "0.10"
install: npm install -g ember-cli
before_script:
  - npm install -g bower
  - bower install
  - npm install
  - cp vendor/ember/index.js vendor/ember/ember.js
script: ember test